zuul:
  routes:
    get:
      path: /get/**
      url: http://httpbin.org/get
    links:
      path: /links/**
      url: http://httpbin.org/links
    images:
      path: /image/**
      url: http://httpbin.org/image
    hello:
      path: /hello/**
      url: http://demo-springboot-odangreaux-project1.7e14.starter-us-west-2.openshiftapps.com

eureka:
  client:
    enabled: false